name: CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: choco install cmake git

      - name: Compile with MSVC
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTS=on
          cmake --build . --config Release

      - name: Run tests
        run: |
          cd build
          ./Release/TestSyriusUtils.exe